name: PDF-Viewer Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.4"

      - name: Install Qt6 and Poppler dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            libpoppler-qt6-dev \
            g++ \
            pkg-config

      - name: Build Application
        run: make ci

      - name: Clang Tidy
        run: |
          make clang
          make tidy
