name: PDF-Viewer Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.4"

      - name: Install Qt6 and Poppler dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            libpoppler-qt6-dev \
            g++ \
            clang \
            lcov \
            pkg-config \
            just 

      - name: Build Application
        run: just ci

      - name: Clang Tidy
        run: |
          just clang
          just create-compile-commands
          just tidy
      - name: test and coverage
        run: |
          just test

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: QT Tests
          path: "*.xml"
          reporter: java-junit
          fail-on-error: true

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          format: lcov
          files: coverage.info
